apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-410
  namespace: default
spec:
  config: '{ "cniVersion": "0.3.1", "name": "macvlan-410", "type": "macvlan", "mode": "bridge", "master": "bond0.410", "ipa
m": { "type": "static" }}'
