apiVersion: v1
data:
  mirror-list: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]

    [[registry]]
       prefix = ""
       location = "registry.redhat.io/multicluster-engine"
       mirror-by-digest-only = true

       [[registry.mirror]]
       location = "{{ quay_fqdn }}/ocp/ocp4/multicluster-engine"

    [[registry]]
       prefix = ""
       location = "quay.io/openshift-release-dev/ocp-release"
       mirror-by-digest-only = true

       [[registry.mirror]]
       location = "{{ quay_fqdn }}/ocp/ocp4/openshift/release-images"

    [[registry]]
       prefix = ""
       location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
       mirror-by-digest-only = true

       [[registry.mirror]]
       location = "{{ quay_fqdn }}/ocp/ocp4/openshift/release"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-30T19:59:02Z"
  name: temp
  namespace: multicluster-engine
